// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi5pe1c94kCH6cwMzGSkvKWmEHT8eq5wc',
    appId: '1:669023696497:web:03e000e2a1220da5d88dd0',
    messagingSenderId: '669023696497',
    projectId: 'glutensearch-55e0d',
    authDomain: 'glutensearch-55e0d.firebaseapp.com',
    storageBucket: 'glutensearch-55e0d.firebasestorage.app',
    measurementId: 'G-HWS4K4QLKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGNtxLmaVRykm_huqmqYMVa2UP14BL6BM',
    appId: '1:669023696497:android:5ec27808f60a1d10d88dd0',
    messagingSenderId: '669023696497',
    projectId: 'glutensearch-55e0d',
    storageBucket: 'glutensearch-55e0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0YLVkePpU_sK-vSC3lN83WLprPUmqh-I',
    appId: '1:669023696497:ios:169d2aed4e2c4c03d88dd0',
    messagingSenderId: '669023696497',
    projectId: 'glutensearch-55e0d',
    storageBucket: 'glutensearch-55e0d.firebasestorage.app',
    iosBundleId: 'com.example.glutenSearch',
  );

}